'\" t
.\"     Title: socketcan-utils
.\"    Author: Markus Becker <mab@comnets.uni-bremen.de>
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 03/15/2011
.\"    Manual: socketcan-utils User Manual
.\"    Source: socketcan-utils
.\"  Language: English
.\"
.TH "SOCKETCAN\-UTILS" "1" "03/15/2011" "socketcan-utils" "socketcan-utils User Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pcan_make_devices \- Create device nodes for each PCAN\-type
.SH "SYNOPSIS"
.HP \w'\fBsocketcan\-utils\fR\ 'u
\fBsocketcan\-utils\fR \fIcount\-of\-device\-node\-for\-each\-type\fR [\fB\-h\fR | \fB\-\-help\fR]
.SH "DESCRIPTION"
.PP
Create "count\-of\-device\-node\-for\-each\-type" device nodes for each PCAN\-type\&.
.PP
This manual page was written for the Debian distribution because the original program does not have a manual page\&. Instead, it has documentation in the GNU
\fBinfo\fR(1)
files\&.
.SH "OPTIONS"
.PP
The program follows the usual GNU command line syntax, with long options starting with two dashes (`\-\*(Aq)\&. A summary of options is included below\&. For a complete description, see the
\fBinfo\fR(1)
files\&.
.PP
\fBcount\-of\-device\-node\-for\-each\-type\fR
.RS 4
The number of devices to create\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show summary of options\&.
.RE
.SH "AUTHOR"
.PP
\fBMarkus Becker\fR <\&mab@comnets\&.uni\-bremen\&.de\&>
.RS 4
Wrote this manpage for the Debian system\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2011 Markus Becker
.br
.PP
This manual page was written for the Debian system (and may be used by others)\&.
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or (at your option) any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in
/usr/share/common\-licenses/GPL\&.
.sp
